services:
  - type: web
    name: groovy-student-crud-api
    env: node
    rootDir: coding/day-05/student-crud/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
